CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE,
    buyeremail TEXT,
    buyername TEXT NOT NULL,
    selleremail TEXT,
    sellername TEXT NOT NULL,
    deliverystreet TEXT,
    deliverycity TEXT,
    deliverystate TEXT,
    deliverypostcode TEXT,
    deliverycountry TEXT,
    requesteddate TEXT,
    issuedate TEXT,
    createdat TEXT,
    updatedat TEXT,
    lastchanged TEXT,
    status TEXT DEFAULT 'DRAFT',
    notes TEXT,
    currency TEXT DEFAULT 'AUD',
    ublxml TEXT
);

