create table if not exists public.parties (
  party_name text not null,
  contact_email text not null,
  created_at timestamptz not null default now(),
  constraint parties_pkey primary key (party_id),
  constraint parties_contact_email_key unique (contact_email),
  constraint parties_contact_email_valid check (
    contact_email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
  )
);

create table if not exists public.app_keys (
  id bigint generated by default as identity not null,
  party_id text not null,
  key_hash text not null,
  created_at timestamptz not null default now(),
  constraint app_keys_pkey primary key (id),
  constraint app_keys_key_hash_key unique (key_hash),
  constraint app_keys_party_id_fkey
    foreign key (party_id) references public.parties (party_id) on delete cascade
);

create index if not exists idx_app_keys_party_id
  on public.app_keys (party_id);

create index if not exists idx_app_keys_key_hash
  on public.app_keys (key_hash);
